[google_service_account]
type = "service_account"
project_id = "reliable-plasma-437208-g3"
private_key_id = "15a1fc4b575b59d7b2951f5faa6e07d4e2a96a64"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDvunwgBJ6HvOlh
I8hpTLjQHQHClsciEZRcSzacddOMJUd8XiYXYo67bxa1IT62aHRe8pa/gq+GUSaO
...
jy7ah0b8S18ZHiyBJEr418k=
-----END PRIVATE KEY-----'''
client_email = "uasmlaselole@reliable-plasma-437208-g3.iam.gserviceaccount.com"
client_id = "112766521944557384247"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/uasmlaselole%40reliable-plasma-437208-g3.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
