[google_service_account]
type = "service_account"
project_id = "reliable-plasma-437208-g3"
private_key_id = "15a1fc4b575b59d7b2951f5faa6e07d4e2a96a64"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDvunwgBJ6HvOlh
I8hpTLjQHQHClsciEZRcSzacddOMJUd8XiYXYo67bxa1IT62aHRe8pa/gq+GUSaO
uaxXSLxlvrN5LDZ5mswxKvvKOPV7bc8yNjLL7hoSOzyvaWRBpMsOfn62/a81RjaI
n54uM3cQnBS5mOHyo5MQT3cP7S0lGRNcq+2TbDNxa471MhaXmAPU40JSKtXd6QkL
96lYLGNQMWEyU7S5dURoEcCuZbMEUmoK5lEuEId20e4Ief4SVMqXbz9ZR1i2yd+c
JOb2Z4pbELwKRNlK8Y8u3dQeU3+AgHT1nOXJzg/Xwzrx220WsHO6S8+L5X8ffMES
prjUCty1AgMBAAECggEAEvtr410k8GU/quFvzRFg0O8lud1r3IFn2KcGpqeYc1Br
CKir0M43tGpnceWKrFw5BWD6xCSk9rhrmoGOk/AT0DqkG27UzBblyZQ4ZnAm1U8s
njKMcyQMtxovA/S5wOOQ8I+I7mnH+yqZcYKyE8EffGvfeD1oJr5XtsLpZT7H2a1W
D7uqa8sBLl0s8812ql1eoXgIiXvY2morhVX42y8HCDjhh3paAlP5sCTBUHHdx08X
b8U5EzZK0o3FA1dM4WBFFlRB4fhsyKOQ90o0mZF61MPM3TyZXQMFewB2Uz8HKpw8
EKC/bYevBy7zNIU+Vk5BwT8ljz6CKDxoPDu6AhzDQQKBgQD3y8iP0YpXJaezbxq1
igRkYoGwfRNLg1sT5Zur20IMa+9H+8R8g9wDHr16VEqEF+VuIC/rVzJE+WJizR0W
OqJ7g5hslfW8ikk/jmY+hFfwzEstDfsG63VLxB43+PlE2lEfMvlLQKo3J3w5lLjT
KPGkw+zDllBa9+uLqo8QRdoqswKBgQD3qlLykbrOrbiDEpnjbe/KpzMIathHvh8p
RM5ENLL6cpoFMxRG2Ah7OqwUXmwLNwnbFcNhNqtQhjhx60xRtV7ZaFxWiKoTC1WH
UAWiu/TPL5h8x7oax1OfVnWcwJUtSBbM1ody5FltIpBszVOpJSpIinRJFCpAgAp5
6d7If2Ku9wKBgHMyLmwFqr12yO6W0SDiJ8aPMOFeVBD/4OBwFp2fUaY6q0OYnLCS
ED73FHkBJJ8iCMvYdM6Ae+Mq2H08A7Co045+D+czE8lxtDmytn+LwOI15yDr5e5C
mgX+B1pYCXHj2GCbrt84EamQVqTiKcYou6WwW6pVf8e6h6snQFj9UD4XAoGBAM6a
QI3oMe0eEHEPQF7wI/xrVHAuKXRXzsjvhB5z0+aHWaMCxGSA7TpXbJulVP5aEJe5
5P4gy/LltQqbXlQ/N/unSnhJk49FgjjZ8YmawBNiQhO9zatvInwmdQCpywg2Pgbs
45tdkJgxIEgTVToiLc7L6UvZTZH2/kZLabTaR2lrAoGAdP2X+t0QPVuFudv4FZ+4
brFNuOBS44wKm5I4ZnstEPT+fp7kA+yATRy0JtZ9Sazx/LxXplabc4dhFCNrlVU5
osf6Ac3sWva276m1ll/tefNp0ScUjpSekCyaM5Bi9l8U7Jk0uNXuOcGaeqAI+qL/
jy7ah0b8S18ZHiyBJEr418k=
-----END PRIVATE KEY-----"""
client_email = "uasmlaselole@reliable-plasma-437208-g3.iam.gserviceaccount.com"
client_id = "112766521944557384247"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/uasmlaselole%40reliable-plasma-437208-g3.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
